confluentinc/kafka-connect-storage-common

partitioner/src/main/java/io/confluent/connect/storage/partitioner/DailyPartitioner.java
partitioner/src/main/java/io/confluent/connect/storage/partitioner/DefaultPartitioner.java
partitioner/src/main/java/io/confluent/connect/storage/partitioner/FieldPartitioner.java
partitioner/src/main/java/io/confluent/connect/storage/partitioner/HourlyPartitioner.java
partitioner/src/main/java/io/confluent/connect/storage/partitioner/PartitionerConfig.java
partitioner/src/main/java/io/confluent/connect/storage/partitioner/TimeBasedPartitioner.java
partitioner/src/main/java/io/confluent/connect/storage/partitioner/TimestampExtractor.java

CC-497: Add timestamp based partitioners.

---

hive/src/main/java/io/confluent/connect/storage/hive/HiveMetaStore.java
hive/src/main/java/io/confluent/connect/storage/hive/HiveUtil.java

Required by: https://github.com/confluentinc/kafka-connect-hdfs/pull/188

HOTFIX: Import recent changes from the hdfs connector

---

common/src/main/java/io/confluent/connect/storage/common/ParentValueRecommender.java
core/src/main/java/io/confluent/connect/storage/StorageSinkConnectorConfig.java

Signed-off-by: Arjun Satish <arjun@confluent.io>

CC-1299: Create AVRO_CODEC ConfigKey

---

partitioner/src/main/java/io/confluent/connect/storage/partitioner/TimeBasedPartitioner.java

Fixes https://github.com/confluentinc/kafka-connect-storage-cloud/issues/109

CC-1489: NPE on records with null timestamp.

---

core/src/main/java/io/confluent/connect/storage/StorageSinkTestBase.java
core/src/main/java/io/confluent/connect/storage/util/DataUtils.java
core/src/main/java/io/confluent/connect/storage/util/DateTimeUtils.java
core/src/test/java/io/confluent/connect/storage/util/DateTimeUtilsTest.java
partitioner/pom.xml
partitioner/src/main/java/io/confluent/connect/storage/partitioner/DailyPartitioner.java
partitioner/src/main/java/io/confluent/connect/storage/partitioner/DefaultPartitioner.java
partitioner/src/main/java/io/confluent/connect/storage/partitioner/HourlyPartitioner.java
partitioner/src/main/java/io/confluent/connect/storage/partitioner/TimeBasedPartitioner.java
partitioner/src/test/java/io/confluent/connect/storage/partitioner/TimeBasedPartitionerTest.java
pom.xml

See  confluentinc/kafka-connect-hdfs#229 for primary reason for this PR
Closes #47

RecordField nested timestamp extraction

---

core/src/main/java/io/confluent/connect/storage/StorageSinkConnectorConfig.java

https://github.com/confluentinc/docs/pull/1015/files

MINOR: Fix docs according to Docs team

---

hive/src/main/java/io/confluent/connect/storage/hive/HiveMetaStore.java

Add a new method that will allow the ability to cascade an alter table command in hive.

Add a method to cascade Hive alter changes

---

core/src/main/java/io/confluent/connect/storage/StorageSinkConnectorConfig.java

Reverts adding append.late.data config to avoid inclusion in a release yet.

CC-2313: Revert and postpone append.late.data config

---

core/src/main/java/io/confluent/connect/storage/StorageSinkTestBase.java
core/src/main/java/io/confluent/connect/storage/util/DataUtils.java
core/src/test/java/io/confluent/connect/storage/util/DataUtilsTest.java
core/src/test/java/io/confluent/connect/storage/util/DateTimeUtilsTest.java
partitioner/src/main/java/io/confluent/connect/storage/partitioner/TimeBasedPartitioner.java
partitioner/src/test/java/io/confluent/connect/storage/partitioner/DailyPartitionerTest.java
partitioner/src/test/java/io/confluent/connect/storage/partitioner/DefaultPartitionerTest.java
partitioner/src/test/java/io/confluent/connect/storage/partitioner/FieldPartitionerTest.java
partitioner/src/test/java/io/confluent/connect/storage/partitioner/HourlyPartitionerTest.java
partitioner/src/test/java/io/confluent/connect/storage/partitioner/TimeBasedPartitionerTest.java
pom.xml

In addition to code added with #48 
Includes #63 
Fixes confluentinc/kafka-connect-hdfs#316, fixes https://github.com/confluentinc/kafka-connect-storage-cloud/issues/152

Add Partitioner unit tests

---

Jenkinsfile

Dependencies built from these projects were found in this project. Changes in these upstream projects may not appear in your build in a timely manner without these changes.
Please edit the suggestion before merging, and if you wish to disable this bot, select Disable.
Created by jenkinsfile-rewriter.

CC-6409: Update Jenkinsfile for 3.2.x

---

partitioner/src/main/java/io/confluent/connect/storage/partitioner/PartitionerConfig.java

Signed-off-by: Greg Harris <gregh@confluent.io>

CC-8816: Document more accurate timezone restrictions

---

core/src/main/java/io/confluent/connect/storage/tools/SchemaSourceTask.java

Adding `complex.keys.headers` configuration to be able to generate complex record `keys` and `headers` for use in tests.

Added complex key/header generation to SchemaSourceTask

---

pom.xml

Correct the issue #137 
backport to 5.3.x

upgrade parquet.version to 1.11.1

---

Jenkinsfile
common/pom.xml
core/pom.xml
format/pom.xml
hive/pom.xml
package-kafka-connect-storage-common/pom.xml
partitioner/pom.xml
pom.xml
wal/pom.xml

We need the release maven plugin for independent releases. Also, some adjustment in version variables
Add the plugin and apply fixes
In all community available connectors formerly shipping with CP
master only. 10.0.x will be created after this commit.

CC-11860: Add release maven plugin and prepare 10.0 release

---

pom.xml

Upgrade hadoop to 2.10.1 and hive to 2.3.7 and pin parent to 6.0.0

---

avatica-shaded/src/main/java/io/confluent/connect/storage/PlaceHolder.java
common/src/main/java/io/confluent/connect/storage/common/SchemaGenerator.java
core/src/main/java/io/confluent/connect/storage/Storage.java
core/src/main/java/io/confluent/connect/storage/StorageSinkConnectorConfig.java
core/src/main/java/io/confluent/connect/storage/schema/StorageSchemaCompatibility.java
htrace-core4-shaded/src/main/java/io/confluent/connect/storage/PlaceHolder.java

MINOR: Javadoc fixes in preparation for the 10.0.0 release

---

htrace-core4-shaded/src/main/java/io/confluent/connect/storage/PlaceHolder.java

javadoc is preventing a release
fix the javadoc

MINOR: fix javadoc for build

---

hive/src/main/java/io/confluent/connect/storage/hive/HiveUtil.java

Previous PR introduced a checkstyle issue (which was not reported in the PR build)
Fix the indentation level

CCMSG-1133: Fix indentation

---

pom.xml

Some updates exist in the parent
Upgrade to the latest patch version
Will merge forward. Recent versions have the same parent

Upgrade common parent to 6.0.3

---

htrace-core4-shaded/src/main/java/io/confluent/connect/storage/PlaceHolder.java

As title says
Indent as expected

MINOR: Fix javadoc after checkstyle upgrade

---

hive/pom.xml
pom.xml

```bash
mvn dependency:tree  | grep log4j
[INFO] +- io.confluent:confluent-log4j:jar:1.2.17-cp2.2:test
[INFO] +- io.confluent:confluent-log4j:jar:1.2.17-cp2.2:test
[INFO] +- io.confluent:confluent-log4j:jar:1.2.17-cp2.2:test
[INFO] +- io.confluent:confluent-log4j:jar:1.2.17-cp2.2:test
[INFO] +- io.confluent:confluent-log4j:jar:1.2.17-cp2.2:test
[INFO] +- io.confluent:confluent-log4j:jar:1.2.17-cp2.2:test
[INFO] |  |  +- org.slf4j:slf4j-log4j12:jar:1.7.30:compile
[INFO] |  |  +- org.apache.logging.log4j:log4j-web:jar:2.6.2:compile
[INFO] |  +- org.apache.logging.log4j:log4j-1.2-api:jar:2.6.2:compile
[INFO] |  |  \- org.apache.logging.log4j:log4j-api:jar:2.6.2:compile
[INFO] |  +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.6.2:compile
[INFO] +- …
```

CC-15909 Exclude standard log4j, update to confluent-log4j to cp8

---

hive/src/main/java/io/confluent/connect/storage/hive/HiveMetaStore.java

DIsable deprecation warning which causes IntelliJ -Werror to fail

---

pom.xml

CI is broken. Locally merged into master and checked that build is fine.

Upgrade parent to 7.2.x

---

pom.xml

Add distributionManagement section which was removed from newer **confluentinc/common** versions

---

avatica-shaded/pom.xml
hive/pom.xml
pom.xml

https://snyk.io/vuln/maven:com.google.protobuf%3Aprotobuf-java

CVE Protobuf: Avatica to 1.9 (protobuf upgrade) and dep management to PB 3.4.0

---

pom.xml

Update common parent and also remove the duplicate jackson dep in pom.
Will release a patch version on 10.0.x

Upgrade common parent to 6.1.6

---

pom.xml

Pint merge failed for PR https://github.com/confluentinc/kafka-connect-storage-common/pull/248 
Creating manual merge commit

Resolve merge conflict for PR 248

---

pom.xml

Reported CVEs associated with current hadoop version.
https://confluentinc.atlassian.net/browse/CCMSG-2025
https://confluentinc.atlassian.net/browse/CCMSG-2023
https://confluentinc.atlassian.net/browse/CCMSG-2016
https://confluentinc.atlassian.net/browse/CCMSG-2015
Update the hadoop version to 2.10.2.

CCMSG-2025: Increment Hadoop version. 

---

pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 5.4.x to 5.5.x)

---

avatica-shaded/pom.xml
pom.xml

CVE fix for netty and avatica core
Fix maven repository protocol from http to https

version bump for netty and avatica dependency

---

pom.xml

https://github.com/confluentinc/schema-registry/issues/2084
https://confluentinc.atlassian.net/browse/RCCA-10639
https://github.com/confluentinc/schema-registry/pull/2514

CC-18808 | Include SR fix to represent Maps correctly

---

pom.xml

Jackson version are being inherited from common and have vulnerabilities. Update the versions.

CC-19097: Update jackson version.

---

hive/pom.xml

CCMSG-2247 Upgrade jettison at kafka-connect-storage-common CVE : [CVE-2022-40149, CVE-2022-40150]

---

htrace-core4-shaded/pom.xml

Using jackson 2.15.x for htrace and upgrading maven-shade-plugin

---

.github/CODEOWNERS

Merge conflict

---

avatica-shaded/pom.xml
common/pom.xml
core/pom.xml
format/pom.xml
hadoop-shaded-guava/pom.xml
hadoop-shaded-protobuf/pom.xml
hive/pom.xml
htrace-core4-shaded/pom.xml
package-kafka-connect-storage-common/pom.xml
partitioner/pom.xml
pom.xml
wal/pom.xml

revert version

---

pom.xml

Update common to bump up guava version

---

hive/pom.xml
pom.xml

Update parent and kryo version for CCMSG-2153, CC-22574, CC-22465, CC-22464, CC-21878

---

pom.xml

https://confluentinc.atlassian.net/browse/CC-22820
https://confluentinc.atlassian.net/browse/CC-22998
https://confluentinc.atlassian.net/browse/CC-23052
Bump common

CC-22820, CC-22998, CC-23052: Fix avro and snappy CVEs

---

.semaphore/project_public.yml
.semaphore/semaphore.yml

This is a routine update from cc-service-bot based on the service.yml in your repo. This PR
should be approved and merged as soon as CI passes.

chore: update repo by service bot

---

pom.xml

https://confluentinc.atlassian.net/browse/CC-22940

Bump netty.version to `4.1.107.Final`

---

avatica-shaded/pom.xml
common/pom.xml
core/pom.xml
format/pom.xml
hadoop-shaded-guava/pom.xml
hadoop-shaded-protobuf/pom.xml
hive/pom.xml
htrace-core4-shaded/pom.xml
package-kafka-connect-storage-common/pom.xml
partitioner/pom.xml
pom.xml
wal/pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 11.2.x to master)

---

.semaphore/project.yml
.semaphore/semaphore.yml
Jenkinsfile
service.yml
sonar-project.properties

Fix merge 10.0.x

---

pom.xml

CC-26360 Bump jackson databind version

---

pom.xml

CC-26360 Bump jackson version

---

hive/pom.xml
pom.xml

fix jackson and snappy CVE

---

pom.xml

Bump jetty version

---

.semaphore/semaphore.yml
pom.xml

Cherry-pick hive version bump to non-legacy branches

Cherry-Pick "Bump hive.version from 2.3.9 to 2.3.10 (#373)"

---

pom.xml

Update protobuf version to address CVE

[CC-29186, CC-29187, CC-29200] Bump common version to bump protobuf version

---

pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 11.1.x to 11.2.x)

---

pom.xml

Bump common-io version

---

pom.xml

Fix pint merge

---

pom.xml

CC-30990: Bump netty version to fix CVE-2024-23945

---

checkstyle/suppressions.xml
core/pom.xml
core/src/main/java/io/confluent/connect/storage/schema/SchemaProjector.java
core/src/main/java/io/confluent/connect/storage/schema/StorageSchemaCompatibility.java
core/src/test/java/io/confluent/connect/storage/schema/SchemaProjectorTest.java
core/src/test/java/io/confluent/connect/storage/schema/StorageSchemaCompatibilityTest.java
pom.xml

Issue - https://confluentinc.atlassian.net/browse/CC-28412
Wiki - https://confluentinc.atlassian.net/wiki/x/R4Hi-/

Fix schema compatibility in S3 sink

---

pom.xml

CC-33008 Bump parquet version

---

format/pom.xml
pom.xml

https://confluentinc.atlassian.net/browse/CC-33024?atlOrigin=eyJpIjoiMjdiMDk1ZWZlODdiNGFhMGI1ZjkxNmEyMjkwODEzM2QiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
Upgraded the parquet-avro version to 1.15.1 in format

Cc 33204 | Upgrade of parquet-avro to 1.15.1

---

.semaphore/semaphore.yml

Replace all occurrences of 's1-prod-ubuntu20-04' with 's1-prod-ubuntu24-04'
