confluentinc/kafka-connect-storage-common

core/src/main/java/io/confluent/connect/storage/schema/StorageSchemaCompatibility.java

Projected `SinkRecord` was missing timestamp information from the original `SinkRecord`

Timestamp information should be copied to projected SinkRecord

---

common/pom.xml
core/pom.xml
format/pom.xml
hive/pom.xml
package-kafka-connect-storage-common/pom.xml
partitioner/pom.xml
pom.xml
wal/pom.xml

The hive-exec library bundles all its dependencies and this creates conflicts
with Connect's libraries (for example, avro-1.8.2 in Connect conflicts with the
avro(-1.7.7) classes bundled in hive-exec). We also need to add commons-lang3
and kryo and avro-mapred here, since they are not pulled in by hive-exec's pom
but required at runtime.
Signed-off-by: Arjun Satish <arjun@confluent.io>

CC-1333: Remove dependency on hive-exec and instead use hive-exec:core

---

core/src/main/java/io/confluent/connect/storage/StorageSinkTestBase.java

Recently added a new method in SinkTaskContext. We don't call it, so we can implement by throwing UnsupportedOperationException.
This only has to be merged to `master`.

MINOR: Fix compilation error due to new method in SinkTaskContext

---

checkstyle/suppressions.xml
core/src/main/java/io/confluent/connect/storage/StorageSinkConnectorConfig.java

This will allow storage-connectors to put late arriving data from a previous time-based partition to be appended to the currently opened partition. This will let users override the existing/default behavior, which rolls new small files for records who do not belong in the currently open partition.
We rely on each connector that uses the config to implement it

CC-2213 New Config Option introduced to handle late-arriving records

---

core/src/main/java/io/confluent/connect/storage/StorageSinkConnectorConfig.java

This configuration property will allow storage sink connectors that support Parquet to compress their output files. 
The signature of the internal method newConfigDef is also changing here and the storage sink connectors that use it will have to adapt to this change.

CC-6565: Add parquet.codec property to enable compression in storage sink connectors

---

hive/src/main/java/io/confluent/connect/storage/hive/HiveConfig.java
hive/src/main/java/io/confluent/connect/storage/hive/HiveSchemaConverter.java
hive/src/test/java/io/confluent/connect/storage/hive/HiveSchemaConverterTest.java

This is PR basically does what this old zombie PR does https://github.com/confluentinc/kafka-connect-storage-common/pull/101 . I made this new PR because the old one was based on the wrong branch and was targeting the wrong branch. 
Once merged, `HiveSchemaConverter` would be able to support logical types: decimal, timestamp, time and date.

CC-147: logical types support for HiveSchemaConverter

---

hive/src/main/java/io/confluent/connect/storage/errors/HiveMetaStoreException.java
partitioner/src/main/java/io/confluent/connect/storage/errors/PartitionException.java
pom.xml

Maven apparently by default does not show warnings, making the `-Werror` a
no-op. Once warnings are turned on, some warnings show up and the build
fails as expected with. This commit also fixes those warnings.

MINOR: Actually show and fail on warnings; fix warnings

---

hive/pom.xml
pom.xml

This commit bumps Hadoop version to 2.10.0 released 10/2019 and Hive version to 2.3.6 released 8/2019.
Muckrake system test run #3352 is passing with this change.

[6.0] CC-3543: Update Hadoop and Hive versions

---

core/src/test/java/io/confluent/connect/storage/util/DataUtilsTest.java
partitioner/src/test/java/io/confluent/connect/storage/partitioner/FieldPartitionerTest.java
partitioner/src/test/java/io/confluent/connect/storage/partitioner/TimeBasedPartitionerTest.java

Tests were failing due to use of deprecated `ExpectedException.none()`. We picked up the new version of JUnit that deprecated this in:
https://github.com/confluentinc/common/commit/10fef4a03b21fc6c4aaad6948bcc1386fcdcc26d
Just switch over to use `assertThrows` as suggested in JUnit release notes - https://github.com/junit-team/junit4/blob/master/doc/ReleaseNotes4.13.md#pull-request-1633-deprecate-expectedexceptionnone

MINOR: Fix tests

---

pom.xml

`jackson-mapper-asl` has CVE issue as described in CC-8170. The library is still pulled in by Hive even after this commit, but at least impact is minimized to those using Hive integration.
Muckrake tests passing runs:
https://jenkins.confluent.io/job/system-test-confluent-platform-branch-builder/3502/
https://jenkins.confluent.io/job/system-test-confluent-platform-branch-builder/3503/

Bump parquet version to remove jackson-mapper-asl dependency

---

core/src/main/java/io/confluent/connect/storage/StorageSinkTestBase.java

This is a preliminary implementation that signals that the new method is not supported yet.

MINOR: Fix build requiring an implementation of errantRecordReporter

---

partitioner/src/main/java/io/confluent/connect/storage/partitioner/PartitionerConfig.java
partitioner/src/test/java/io/confluent/connect/storage/partitioner/PartitionerConfigTest.java

The `timezone` configuration is not being validated when the `TimeBasedPartitioner` is not set. This results in a runtime error when the `rotate.schedule.interval.ms` is used and an invalid or no `timezone` value is set. [Parent ticket](https://confluentinc.atlassian.net/browse/CC-8815) 
Validate the `timezone` configuration whenever set.
Secondary checks that depend on the timezone configuration should be added to all connectors that need them. For example in the S3 sink we expect the `timezone` configuration to be set when `rotate.schedule.interval.ms` is used.

CC-9779: PartitionerConfig should perform basic timezone validation

---

hive/pom.xml

This PR addresses a CVE caused by `jetty-all 7.6.0.v20120127`. 
Exclude the `jetty-all` dependency that is brought in by `kafka-connect-storage-hive`, same solution as in [gcp-dataproc](https://github.com/confluentinc/kafka-connect-gcp-dataproc/blob/master/pom.xml#L353-L356) and [object-store-source](https://github.com/confluentinc/kafka-connect-object-store-source/blob/master/sink-integration-tests/pom.xml#L190-L193) connectors. 
Tested relevant HDFS and HDFS3 connectors:

CC-8704: Exclude jetty from hcatalog - CVE

---

format/pom.xml
hive/pom.xml

`parquet-avro` pulls in `parquet-jackson` which is a shaded jackson library that pulls in many CVEs in a lot of our storage connectors
exclude `parquet-jackson` and shade a clean jackson version using the same strategy
https://repo1.maven.org/maven2/org/apache/parquet/parquet-jackson/1.11.0/parquet-jackson-1.11.0.pom
this should address `parquet-jackson` in all storage connectors
made sure parquet files were successfully written using the S3 connector
ran system tests for [S3](https://jenkins.confluent.io/job/system-test-confluent-platform-branch-builder/4102/) and [HDFS](https://jenkins.confluent.io/job/system-test-confluent-platform-branch-builder/4105/)
backport to `5.4.x` where CVEs were caught

remove parquet-jackson dependency causing CVEs

---

hive/pom.xml
pom.xml

A number of dependency bring `log4j` as a transitive dependency. `log4j` has reached end of life, and has a critical security issue
replace it with a confluent repackaged version that has security patches.

SEC-1034: log4j migration to confluent repackaged version

---

pom.xml

This pull request updates `confluent-log4j` from `1.2.17-cp1` to `1.2.17-cp2`. The former had a few accidental commits that made the repackaged version slightly different than the upstream `log4j`. `1.2.17-cp2` fixes the issue and applies a CVE fix (and no additional code changes) to the upstream `log4j:1.2.17`.
Update `1.2.17-cp1` to `1.2.17-cp2`

SEC-1334: update confluent-log4j version

---

hive/pom.xml
pom.xml

This pull request cherry-picks a commit from `master` to add explicit `io.confluent:confluent-log4j` dependency, because we blacklist the (vulnerable) tranistive dependency `log4j:log4j` of `org.slf4j:slf4j-log4j12` explicitly in `common`. `io.confluent:confluent-log4j` is a drop-in replacement of `log4j:log4j` with a fix for the vulnerability.

SEC-1307: Backport "log4j replacement with confluent repackaged version"

---

hive/pom.xml

UPDATE: The fix was added (dependency was excluded) in gcs,azure blob and hdfs connectors. We should make a call whether this fix needs to be in storage-common
Resolving connector CVE for jackson-mapper-asl
straight forward exclusion of the transitive dependency, since it isn't used by the connector.
HDFS sink and GCS sink
Branch to be tested against Muckrake.
Understand testing for all connectors that use `kafka-connect-storage-common` for these fixes

CC-12005: Exclude vulnerable dependency jackson mapper asl

---

hive/pom.xml
pom.xml

Commons codec is a CVE that applies to all the storage connectors.
Adding here to resolve across the board
Backporting to 5.4.x seems reasonable. Will merge forward

Update commons codec to 1.15 to resolve CVE and exclude zookeeper test jar

---

htrace-core4-shaded/pom.xml
htrace-core4-shaded/src/main/java/io/confluent/connect/storage/PlaceHolder.java
pom.xml

The HDFS connector (Hadoop v2) depends on a few transitive dependencies that are old and are shading a version of jackson that has CVEs associated with it. 
We are reshading this dependency by removing the old jackson version and replacing it with a newer one that does not have CVEs. HDFS connector can import this dependency and get a clean htrace-core4 package.

Reshade transitive dependency htrace-core4 with newer jackson to remove CVEs

---

core/src/main/java/io/confluent/connect/storage/StorageSinkConnectorConfig.java

The incident RCCA https://confluentinc.atlassian.net/browse/RCCA-1273 uncovered that certain properties were not being configured properly to be used in the connector
This additionally brought to light that in the AvroDataConfig(props) method, the property name needs to match SR's property name https://github.com/confluentinc/schema-registry/blob/778f1e5cca9ebcc2cfc1876c617afb81ed3e5ea4/avro-data/src/main/java/io/confluent/connect/avro/AvroDataConfig.java#L40
Correct SR schemas cache size property name for AvroDataConfig
TODO

Correct SR schemas cache size property name for AvroDataConfig

---

htrace-core4-shaded/pom.xml

Pom files of the old jackson version where preserved in htrace-core4, which confuses the CVE scanner. 
The actual files are correct
Adjust the exclusions correctly
10.0.x and newer

MINOR: Fix pom metadata in htrace shaded dependency

---

avatica-shaded/pom.xml
htrace-core4-shaded/pom.xml

The new modules were introduced after the creation of 10.0.x and were merged on that branch. 
Their version needs to be adjusted manually on the `master` branch.
Set version `10.1.0-SNAPSHOT` on `master` for the new modules
Only `master`

MINOR: Fix versions of modules added after the creation of 10.0.x branch

---

core/src/main/java/io/confluent/connect/storage/StorageSinkConnectorConfig.java

Changing the default required the release of a major version
Switch the default to enhanced avro schema support
Only 10.0.x and beyond

CC-1360: Enable enhanced avro schema support by default in storage sink connectors

---

core/src/main/java/io/confluent/connect/storage/util/DateTimeUtils.java
core/src/test/java/io/confluent/connect/storage/util/DateTimeUtilsTest.java

Doing time-zone aware calculation for scheduled rotation
As stated in https://github.com/confluentinc/kafka-connect-storage-cloud/issues/375 :
When scheduled rotation is enabled, on the day of the DST changes (25 hour day), during the last hour of the day kafka connect s3 sink would be rotating files after every record, producing a lot of tiny files.
Perform timezone aware date-time calculations.
Ready to be merged to master and should be safe to roll-back.

Fix time-zone aware calculation for scheduled rotation between daylight savings and standard time

---

partitioner/src/main/java/io/confluent/connect/storage/partitioner/TimeBasedPartitioner.java
partitioner/src/test/java/io/confluent/connect/storage/partitioner/TimeBasedPartitionerTest.java

Currently, if S3 sink connector is configured as follows:
```
"connector.class":"io.confluent.connect.s3.S3SinkConnector",
"timestamp.extractor":"RecordField",
"timestamp.field":"ts.field",
"partitioner.class":"io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
...
```
It can handle records, where the timestamp field has a string literal with ISO-8601-formatted date:
```
{"ts.field":"2000-08-20T4:05:30.799044","value":"xyz"}
```
But fails to handle a record, where the timestamp field has a string literal with Unix time:
```
{"ts.field":"1597904371234","value":"xyz"}
```

CC-11532: TimeBasedPartitioner to extract timestamp from a string literal as unixtime or ISO-8601-formatted date.

---

core/pom.xml
format/pom.xml
hive/pom.xml
pom.xml

The current cc-docker image has kafka-connect-avro-converter in multiple places:
/usr/share/java/connectors/plugins/converters
/opt/confluent/libs
S3 sink, ADLS2, GCP functions, Azure functions, Dataproc sink, Azure blob storage, GCS sink connectors.
It’s problematic to have the same library in multiple locations, and we need to worry about version consistency. We want to have this library in /usr/share/java/connectors/plugins/converters only, and treat it as another plugin.
Now that we have the `avro-data` dependency available, remove `avro-converter` dependency from downstream blob connectors https://confluentinc.atlassian.net/browse/CC-7169
Tested with IT's in Azure Blob Storage https://github.com/confluentinc/kafka-connect-azure-blob-storage/pull/125

CC-13001: Remove avro-converter dependency and add avro-data dependency

---

hive/pom.xml

jamon runtime is causing build errors for some storage connectors i.e [HDFS](https://github.com/confluentinc/kafka-connect-hdfs/tree/10.0.x)
due to https://www.jfrog.com/jira/browse/RTFACT-16033, suppressing consistency checks is not an option
pin this dependency and release a new version of storage common
pinned the snapshot version to HDFS and made sure it built and ran all of the hive tests correctly
release `v10.0.2` for the storage connectors to use

MINOR: pin jamon dependency to fix build errors

---

avatica-shaded/pom.xml
htrace-core4-shaded/pom.xml
pom.xml

there are still multiple CVEs (jackson-databind and http-components)
bump common parent and the CVEs versions to clean ones (twistlock shows clean)
bug fix version bumps so harmless
built a local version and tried it downstream with HDFS and everything passed
`10.0.x` where the CVEs are reported

CC-13056: address http and jackson CVEs

---

pom.xml

Currently the parent pom uses `${project.version}` for the submodules `kafka-connect-storage-common`, `kafka-connect-storage-core`, `kafka-connect-storage-format`, `kafka-connect-storage-partitioner`, `kafka-connect-storage-wal`. 
This becomes an issue when building connectors that use this parent, as the `${project.version}` in a parent pom refers to the version of the child, not the parent. The value gets re-interpreted by maven every time on a build and refers to the version of the project built at that moment, not the version of the parent. This has resulted in connector build job errors as `SNAPSHOT` dependencies are not allowed. 
```
01:01:13  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project …
```

CC-13532: Pin storage common version in parent

---

avatica-shaded/pom.xml

Looks like we have two sets of classes in `org.apache.http` package: one of the correct version(`4.5.13`) and one of the old version(`4.5.2`).
```
mvn clean package
...
unzip kafka-connect-storage-common-avatica-shaded-10.0.4-SNAPSHOT.jar -d kafka-connect-storage-common-avatica-shaded-10.0.4-SNAPSHOT
...
cd kafka-connect-storage-common-avatica-shaded-10.0.4-SNAPSHOT
...
find . -name "HttpClient.class"
./org/apache/calcite/avatica/org/apache/http/client/HttpClient.class
./org/apache/http/client/HttpClient.class
...
cat org/apache/http/client/version.properties|grep release
info.release   = 4.5.13
...
cat org/apache/calcite/avatica/org/apache/http/client/version.properties|grep release
info.release   = 4.5.2
```
Exclude the `org/apache/httpcomponents/**` package from the shaded JAR.

Update pom to exclude org/apache/http from the shaded JAR.

---

avatica-shaded/pom.xml

Exclude commons-codec from the Avatica shaded JAR and include its newer version separately to resolve CVE

---

pom.xml

HttpClient dependency version contains a CVE: https://nvd.nist.gov/vuln/detail/CVE-2020-13956
Upgrade to HttpClient 4.5.13
The purpose is to start a discussion for https://confluentinc.atlassian.net/browse/CC-13830.
Let's discuss whether additional tests are needed. 
Merge to master

CC-13830: upgrade  org.apache.httpcomponents:httpclient version to 4.5.13 to address CVE

---

partitioner/src/main/java/io/confluent/connect/storage/partitioner/TimeBasedPartitioner.java

Throwing `ConnectException` but failure is caused by malformed data. 
Revise to `DataException` for a more appropriate exception type.
Targeting `10.0.x`

MINOR: Use PartitionException instead of ConnectException when unable to extract the record timestamp in TimeBasedPartitioner

---

wal/src/main/java/io/confluent/connect/storage/wal/FilePathOffset.java
wal/src/main/java/io/confluent/connect/storage/wal/WAL.java

The `WAL` interface does lacks a function to support extracting latest offsets from `WAL` files. 
Add a function to support extracting offsets from `WAL` files and a class to keep track of the returned offset-path value pair. 
Targeting `10.0.x` for new release.

WAL: created FilePathOffset class, and added extractLatestOffsetFromWAL to interface

---

pom.xml

In the parent pom, `version` and `kafka.connect.storage.common.version` are misaligned. 
Update `kafka.connect.storage.common.version` to `10.1.0-SNAPSHOT` .
Fixing on `master`

MINOR: Align versions in parent pom

---

format/pom.xml
hive/pom.xml
htrace-core4-shaded/pom.xml
htrace-core4-shaded/src/main/java/io/confluent/connect/storage/PlaceHolder.java
pom.xml

lots of CVEs leftover in 5.2.x and on
resolve them using various methods
https://twistlock.tools.confluent-internal.io/#!/monitor/vulnerabilities/images/ci?search=storage-common:PR-185
all CVEs are resolved, the ones left are in S3 and HDFS
except for guava which i was unable to resolve because there is a backwards incompatible change that HDFS relies on
some CVEs have no resolution i.e `commons-collection`
other CP connectors (S3 + HDFS)
tested against HDFS connector locally
backport to `5.2.x`

CC-14522: resolve hadoop, jackson, thrift, log4j, commons-collection, bean-utils, netty, zookeeper, commons-codec, and httpclient CVEs

---

pom.xml

upgrading thrift is a breaking change for HDFS
revert thrift to a working version `0.9.3`
tested with HDFS
backport to `5.2.x` where this version was pinned

MINOR: revert thrift back 0.9.3

---

hive/pom.xml

`jetty-all` is a CVE that is getting pulled into HDFS
exclude it
tested against HDFS
backport to `5.2.x` where the CVE needs to be fixed

MINOR: exclude jetty-all to address CVE

---

pom.xml

Critical CVE for jackson-mapper
Upgrade to redhat version which has no CVE

Upgrade jackson-mapper-asl to 1.9.14.jdk17-redhat-00001 and fix CVE

---

hive/pom.xml

https://github.com/confluentinc/kafka-connect-storage-common/pull/138 introduced an issue where the HDFS connector needs this dependency and fails if it is not present
```
[2021-05-05 15:32:36,071] ERROR WorkerSinkTask{xxx} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:187)
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/codehaus/jackson/map/ObjectMapper
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2261)
at com.google.common.cache.LocalCache.get(LocalCache.java:4000)
at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4789)
at org.apache.hadoop.hdfs.KeyProviderCache.get(KeyProviderCache.java:76)
at …
```

CCMSG-1072: stop excluding necessary jackson-mapper-asl dependency

---

pom.xml

When the versions of zk differ from Kafka tests and common, tests break
Keep getting ZK as transitive dependency at the version that is defined in https://github.com/confluentinc/common/blob/master/pom.xml#L94

MINOR: Keep zookeeper as transitive dependency inherited from common parent pom

---

pom.xml

CVE-2021-29425 affect commons-io version 2.4
Upgrade to commons-io 2.7

Upgrade commons-io to 2.7 and address CVE-2021-29425

---

hive/src/main/java/io/confluent/connect/storage/hive/HiveUtil.java

We need to update the HiveUtil.createTable interface by adding the topic name so we can decouple the hive table name from the location path.
Add an extra topic argument.

CCMSG-1133: Decouple topic name from hive table name

---

hive/pom.xml
pom.xml

Outdated dependency
pin version only in the hive module
Applies to 5.4.x or newer

CC-15305: Upgrade transitive dependency commons-compress to 1.21

---

pom.xml

Upgrade Jetty Version
- [x ] yes
common, rest-utils, etc

Upgrade Jetty server dependency to 9.4.43.v20210629

---

pom.xml

https://github.com/confluentinc/kafka-connect-hdfs/issues/578
Upgrade hive to 2.9.3

update hive dependency to 2.9.3 for backwards compatibility with older hive versions

---

core/pom.xml

mockito-all was removed in mockito 2.x

remove usage of deprecated mockito-all

---

pom.xml

The version is defined upstream confluent/common but is needed downstream by users of this repo. It makes sense to define it here.

Declare protobuf-java in dependencyManagement to get version from common parent

---

pom.xml

Minor version update(backwrads compatible) to 2.13.2.
Add related jackson dependencies to dependencymanagement to guard against jackson version mismatches.

Bump jackson versions to 2.13.2 to address cve's

---

avatica-shaded/pom.xml

This pin is outdated. Morever, we are updating something in the parent level now so let's use that.
Original basis for the pin was just a usage of something recent at the time, before we could get a current version fromelsewhere.
https://github.com/confluentinc/kafka-connect-storage-common/pull/159/files#r516434514
We are already using a different jackson version in the hdfs connector without issue 
https://github.com/confluentinc/kafka-connect-hdfs/blob/10.1.x/pom.xml#L205
So this pin doesn't serve anything anymore other than to give us CVE tickets.

CCMSG-1737: Remove pinning of jackson from avatica shaded

---

pom.xml

CVE-2020-36518 was reported
updated jackson-databind to 2.13.2.1 to resolve

CCMSG-1751 updated jackson-databind to 2.13.2.1 to resolve CVE-2020-36518

---

hive/pom.xml
pom.xml

List of CVE that this PR addresses. 
https://confluentinc.atlassian.net/browse/CCMSG-1900
https://confluentinc.atlassian.net/browse/CCMSG-1894
https://confluentinc.atlassian.net/browse/CCMSG-1896
https://confluentinc.atlassian.net/browse/CCMSG-1901
https://confluentinc.atlassian.net/browse/CCMSG-1904
https://confluentinc.atlassian.net/browse/CCMSG-1908
https://confluentinc.atlassian.net/browse/CCMSG-1910
https://confluentinc.atlassian.net/browse/CCMSG-1912
Since all of these dependencies are brought in through hive we have to override those dependencies through dependency management. Some of the dependencies can be removed.
Tested this locally by installing the maven artefact and using it in hdfs sink connector. All test tests pass with the updated dependencies, except one for kerberos …

CCMSG-1906: Adress CVEs for ant, jsp, groovy, derby, netty and orc. 

---

hive/pom.xml
pom.xml

This is a cherry-pick of #237 
List of CVE that this PR addresses.
https://confluentinc.atlassian.net/browse/CCMSG-1900
https://confluentinc.atlassian.net/browse/CCMSG-1894
https://confluentinc.atlassian.net/browse/CCMSG-1896
https://confluentinc.atlassian.net/browse/CCMSG-1901
https://confluentinc.atlassian.net/browse/CCMSG-1904
https://confluentinc.atlassian.net/browse/CCMSG-1908
https://confluentinc.atlassian.net/browse/CCMSG-1910
https://confluentinc.atlassian.net/browse/CCMSG-1912
Since all of these dependencies are brought in through hive we have to override those dependencies through dependency management. Some of the dependencies can be removed.
Tested this locally by installing the maven artefact and using it in hdfs sink connector. All test tests pass with the updated …

CCMSG-1906: Adress CVEs for ant, jsp, groovy, derby, netty and orc.

---

avatica-shaded/pom.xml
hive/pom.xml

protobuf used in avatica shaded has a vulnerability.
added protobuf version in  avatica shaded pom from main pom.
For manual testing, created a kafka-connect-storage SNAPSHOT jar and tested hdfs sink connector (having this snapshot jar) using docker playground.
```
➜  connect-hdfs2-sink git:(master) ✗ CONNECTOR_ZIP=/Users/ajain/projects/kafka-connect-hdfs/target/components/packages/confluentinc-kafka-connect-hdfs-10.0.9-SNAPSHOT.zip ./hdfs2-sink.sh
16:38:59 ℹ️ 💫 Using default CP version 7.1.1
16:38:59 ℹ️ 🎓 set TAG environment variable to specify different version, see https://kafka-docker-playground.io/#/how-to-use?id=🎯-for-confluent-platform-cp
16:38:59 ℹ️ 👷🛠 Re-building Docker image vdesabou/kafka-docker-playground-connect:7.1.1 to include confluentinc/kafka-connect-hdfs:latest
[+] …
```

CCMSG-1740: update protobuf version in avatica

---

hadoop-shaded-protobuf/README.md
hadoop-shaded-protobuf/pom.xml
pom.xml

Hadoop Shaded module contains protobuf-java with vulnerability and it is getting used in hdfs3 sink connector
Added hadoop shaded module which contains latest protobuf-java without vulnerability
https://github.com/confluentinc/kafka-connect-object-store-source/pull/274
Tested by using local storage-common SNAPSHOT in hdfs3 sink connector in docker playground:
```
➜  connect-hdfs3-sink git:(master) ✗ TAG=5.3.8 CONNECTOR_ZIP=/Users/ajain/projects/kafka-connect-hdfs3/target/components/packages/confluentinc-kafka-connect-hdfs3-1.1.14-SNAPSHOT.zip  ./hdfs3-sink.sh
23:38:42 ℹ️ 🚀 Using specified CP version 5.3.8
23:38:42 ℹ️ 👷🛠 Re-building Docker image vdesabou/kafka-docker-playground-connect:5.3.8 to include confluentinc/kafka-connect-hdfs3:latest
[+] Building 43.8s (6/6) FINISHED …
```

CCMSG-1654: Add hadoop shaded protobuf module

---

hadoop-shaded-protobuf/pom.xml

The parent version in Hadoop shaded is not the branch's latest snapshot version
Starts getting this issue after pint merge of #244 
updated parent version in Hadoop shaded

CCMSG-1654: fix parent in hadoop shaded

---

pom.xml

`slf4j-log4j12` has vulnerabilites and is being replaced with `slf4j-reload4j`
https://confluentinc.atlassian.net/browse/CCMSG-1972
Adding a dependency on `slf4j-reload4j` in this "parent" pom, to use in child connector plugins.
Will be used in child connect plugins

Add a dependency on slf4j-reload4j to used child plugins

---

pom.xml

Adding range in version can lead to variety of `kafka.version` in common. All of which may not be available for public builds. 
Pin parent `common` version, so the dependencies imported remain constant and does not change with time.

Pin common version to 7.2.1

---

pom.xml

https://confluentinc.atlassian.net/browse/CCMSG-2042
Tested this upgrade on kafka-connect-s3 where the hadoop dependency is being inherited as is. This was done by installing it locally and then running the tests in s3.

Bump up hadoop version to 2.10.2.

---

pom.xml

confluent-log4j needs to be replaced by reload4j for cve fix. Ticket : 
https://confluentinc.atlassian.net/browse/CC-15904

CC-15904 replace confluent-log4j with reload4j

---

pom.xml

Not needed after https://github.com/confluentinc/common/pull/485.

Remove Jackson version pinning.

---

pom.xml

https://confluentinc.atlassian.net/browse/CCMSG-2275
According to the release notes for 2.8.0 it is fully compatible with 2.7 so this bump should not cause a breaking change. 
https://github.com/apache/commons-io/blob/master/RELEASE-NOTES.txt

CCMSG-2275: Update commons-io to resolve CVE

---

core/src/main/java/io/confluent/connect/storage/util/DataUtils.java
core/src/test/java/io/confluent/connect/storage/util/DataUtilsTest.java

A data exception if thrown can include struct information which contain user data. This is a security concern.
Remove struct from the exception logging.

CCMSG-2370: Remove logging struct in exception 

---

core/src/main/java/io/confluent/connect/storage/StorageSinkConnectorConfig.java

Expose the config to represent map types correctly in parquet output format.

CC-18808 | Expose config to enable representation of Maps correctly.

---

pom.xml

The netty dependency is out of date and should be updated to resolve CVE-2022-41915 in the connectors that use this common parent

Update netty to 4.1.86 to to address CVE-2022-41915 and put in line with Kafka version

---

hive/src/main/java/io/confluent/connect/storage/hive/HiveSchemaConverter.java
hive/src/test/java/io/confluent/connect/storage/hive/HiveSchemaConverterTest.java

Some logical connect data types are not correctly inferred to their hive counterpart. These include Date and Timestamp datatypes which are inferred as `int` and `long` previously. However in the `orc` writer these are inserted as Timestamp and Dates respectively which causes data with such datatypes to fail when queried in hive. Time logical type can also either be `int` or `long`. 
There is also a bug in the recursive parsing logic where if logical types are not handled if nested inside a struct, array or map. This is because in case of struct the `convertPrimitiveMaybeLogical` is never reached as the recursive calls always goes to the not logical convert method. 
Assign the correct hive data types for the logical connect types. The hive logical conversion is not used currently in any of …

CCLOG-2401: Parse logical types correctly for hive schemas. 

---

Jenkinsfile
pom.xml

There are two issues we are fixing here - 
1. Not able to access ${confluent.maven.repo} property. 
```
[ERROR]     Non-resolvable parent POM for io.confluent:kafka-connect-storage-common-parent:10.0.17-SNAPSHOT: Could not transfer artifact io.confluent:common:pom:6.1.9 from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 21, column 13: Cannot access ${confluent.maven.repo} using the registered transporter factories: WagonTransporterFactory: Unsupported transport protocol -> [Help 2]
```
Fix for this is already explained in this PR - https://github.com/confluentinc/kafka-connect-elasticsearch/pull/419
2. …

Minor: Fix build errors

---

pom.xml

- https://confluentinc.atlassian.net/browse/CCMSG-2388
- Protobuf version 3.19.4 has vulnerabilities.
- Bring updated protobuf dependency from parent pom. 
Reference - https://github.com/confluentinc/kafka-connect-elasticsearch/pull/419

CCMSG-2388: Bump protobuf.version to 3.19.6 to resolve CVEs

---

pom.xml

- This issue was encounter earlier as well and was fixed in this PR - https://github.com/confluentinc/kafka-connect-storage-common/pull/273 but this change got recently reverted - https://github.com/confluentinc/kafka-connect-storage-common/pull/298 and again caused the same issue. 
Error stacktrace - ```NoClassDefFoundError: org/apache/hadoop/mapreduce/lib/output/FileOutputFormat```
- Move back to older version - v1.11.2
- @pbadani is manually overriding the version in s3 connector and verifying that this fixes the issue and also ensuring no new CVEs are added - https://confluent.slack.com/archives/C04PX7REHRQ/p1676622604087989?thread_ts=1676549999.603739&cid=C04PX7REHRQ

RCCA-10996: Update parquet.version to 1.11.2 to fix NoClassDefFoundError

---

core/src/main/java/io/confluent/connect/storage/schema/SchemaCompatibilityResult.java
core/src/main/java/io/confluent/connect/storage/schema/SchemaIncompatibilityType.java
core/src/main/java/io/confluent/connect/storage/schema/StorageSchemaCompatibility.java
core/src/test/java/io/confluent/connect/storage/schema/StorageSchemaCompatibilityTest.java

Return the schema incompatibility reason so that it can be logged in downstream connectors to enhance logging.

CC-19464 | Return the reason for schema incompatibility along with the boolean result.

---

hadoop-shaded-guava/README.md
hadoop-shaded-guava/pom.xml
pom.xml

Hadoop Common 3.2.4 has a vulnerability
Hadoop Common 3.3.6 uses hadoop shaded guava in 3.3.6 version in sftp connector use case. 
Hadoop guava also has a vulnerability and can't be used
Without hadoop guava it fails with error:
```
[ERROR] testPoll(io.confluent.connect.sftp.sink.ParquetWriterTest)  Time elapsed: 0.319 s  <<< ERROR!
01:51:59  java.lang.NoClassDefFoundError: org/apache/hadoop/thirdparty/com/google/common/collect/Interners
01:51:59  	at io.confluent.connect.sftp.sink.ParquetWriterTest.testPoll(ParquetWriterTest.java:61)
01:51:59  Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.thirdparty.com.google.common.collect.Interners
01:51:59  	at io.confluent.connect.sftp.sink.ParquetWriterTest.testPoll(ParquetWriterTest.java:61)
```
Added Hadoop-shaded guava with the …

Add hadoop shaded guava

---

.semaphore/project.yml
.semaphore/semaphore.yml
Jenkinsfile
service.yml
sonar-project.properties

Cherry-pick the changes to the lowest valid .x branch and open a PR.
Then [pint merge](https://jenkins.confluent.io/job/tools-autotasks/job/tools-autotasks/job/apply-pint-merge/build?delay=0sec) the changes from that .x branch.
1) Disables the deploy in the Jenkinsfile.
2) Adds the service-bot config (service.yml) and semaphore files generated by service-bot
[Read the background and motivation](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3033867557/CI+System+Migration+Jenkins-+Semaphore#Background-and-Motivation)  
Please merge this PR ASAP because we plan on shutting down Jenkins by the end of the year.

Migration: Jenkins -> Semaphore

---

hive/pom.xml
pom.xml

Reverts confluentinc/kafka-connect-storage-common#363
* With hive versions >= 4.0.0, the core jars are no longer built and distributed by the Apache Hive project. They now only supply a fat jar which bundles a number of other dependencies as well. (please see [HIVE-25531](https://issues.apache.org/jira/browse/HIVE-25531) for more details).
* This change has now been reverted in the master branch due to the reasons explained here: [HIVE-26220](https://issues.apache.org/jira/browse/HIVE-26220). (tl;dr, core-jars will be re-introduced in hive-exec versions >= 4.1.0)
* The extra dependencies in the fat jar introduce critical vulnerabilities in the HDFS3 connector builds, hence we will be reverting to the use of core-jars.

Revert "CC-25176: Bump Hive Version"

---

pom.xml

Bump netty-version to fix CVEs in child repositories.

Bump `netty.version` to `4.1.108.Final`

---

partitioner/src/test/java/io/confluent/connect/storage/partitioner/HourlyPartitionerTest.java
pom.xml

joda-time version 2.9.6 does not handle the daylight savings for some timezones and was formatting the time incorrectly. 
Example, for America/Santiago timezone, the timezone was formatted incorrectly when the day light savings ended
RCCA-19503
Fix the dependency to v2.10.1 which has the fix for same.

CC-27029 Bump joda-time version

---

pom.xml

Bump `hive.version` to 2.3.10 to upgrade hive-exec in downstream projects.

Bump hive.version from 2.3.9 to 2.3.10

---

pom.xml

Intermittent fix for the below error
```
caused by DownloadFailedException: Download failed, unable to retrieve 'https://s3-us-west-2.amazonaws.com/confluent-packaging-tools/nvd.nist.gov/nvdcve-1.1-modified.meta'; Error downloading file https://s3-us-west-2.amazonaws.com/confluent-packaging-tools/nvd.nist.gov/nvdcve-1.1-modified.meta; unable to connect.
```

Skip Dependency Check to Unblock Release

---

pom.xml

CC-29502: Vulnerable dependency "org.apache.avro_avro:1.11.3" for kafka-connect-storage-cloud:master-latest
Bump apache avro to 1.11.4

CC-29502: Bumped apache avro to resolve CVE

---

pom.xml

Bump jetty-version to fix [CVE-2024-8184](https://nvd.nist.gov/vuln/detail/CVE-2024-8184)

Bump jetty version to fix CVE
